name = "ecotracker-backend"
main = "src/index.py"
compatibility_date = "2024-03-20"
compatibility_flags = ["python_workers"]

# Configuración de la base de datos D1
[[d1_databases]]
binding = "DB"
database_name = "ecotracker-db"

database_id = "85a2c830-4394-4402-8f6e-1d94541bdd38"